# Generated by Django 6.0.2 on 2026-04-21 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_bundledetail_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundledetail',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Debe ser mayor o igual a 0.')]),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Debe ser mayor o igual a 0.')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='min_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Debe ser mayor o igual a 0.')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Debe ser mayor o igual a 0.')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Debe ser mayor o igual a 0.')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Debe ser mayor o igual a 0.')]),
        ),
    ]
