# Generated by Django 6.0.3 on 2026-04-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_min_stock_alter_item_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
